port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
authentication:
  - "test:test"
log-level: debug
allow-lan: true
bind-address: "*"
mode: Rule

proxies:
  - {name: node, type: trojan, server: github.com, port: 443, password: my_password }

rules:
  - MATCH,node